/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project3;

import bitcamp.project3.command.MainMenu;
import bitcamp.project3.util.Login;
import bitcamp.project3.util.Prompt;
import bitcamp.project3.vo.User;

public class App {
    String[] loginMenus = {"로그인", "회원가입", "비밀번호 찾기", "종료"};
    MainMenu mainMenu = new MainMenu();

    public static void main(String[] args) {
        new App().init();
    }

    void init() {
        System.out.println("[로그인]");
        while (true) {
            printLoginMenu();
            String command = Prompt.input(">");
            try {
                int menuNo = Integer.parseInt(command);
                String menuTitle = getloginMenuTitle(menuNo, loginMenus);
                if (menuTitle == null) {
                    System.out.println("유효한 메뉴가 아닙니다.");
                } else {
                    processLogin(menuTitle);
                    break;
                }
            } catch (NumberFormatException ex) {
                System.out.println("숫자로 메뉴 번호를 입력하세요.");
            }
        }
    }

    private void processLogin(String menuTitle) {
        switch (menuTitle) {
            case "로그인":
                User user = Login.loginUser();
                if (!(user == null)) {
                    mainMenu.execute(user);
                    break;
                } else {
                    System.out.println("횟수 초가 - 초기화면으로 돌아갑니다.");
                    break;
                }
            case "회원가입":
                Login.authUser();
                break;
            case "비밀번호 분실":
                Login.reSetUserPassword();
                break;
            case "종료":
                System.out.println("시스템을 종료합니다.");
                System.exit(0);
            default:
                System.out.println("없는 메뉴입니다.");
                break;
        }
    }

    boolean isvalidatemenu(int menuNo, String[] loginMenus) {

        return menuNo >= 1 && menuNo <= loginMenus.length;
    }

    String getloginMenuTitle(int menuNo, String[] loginMenus) {
        return isvalidatemenu(menuNo, loginMenus) ? loginMenus[menuNo - 1] : null;
    }

    private void printLoginMenu() {
        int count = 1;
        for (String menu : loginMenus) {
            System.out.printf("%s. %s\n", count++, menu);
        }
    }
}
